### ISSUE TITLE
New tag for Laravel 6

### ISSUE THREAD

**Issue by yvesnetalis** [casperboone/laravel-zabbix-graph#2]
Hello @casperboone , thank you for merging las pull request. Could you add new tag for composer update :wink: ?

**Comment by casperboone** [comment]
Sorry for the delay, just tagged a new version. No longer using this package myself, hence I'm no longer actively maintaining it and don't keep a close eye on it 😅.

**Comment by yvesnetalis** [comment]
no problem, thank you for update :)
